@echo off
TITLE MARIE Launcher
echo [MARIE] Starting Brain Server (Port 8000)...
start /MIN "MARIE Brain" python server_reasoning.py
echo [MARIE] Starting Voice Server (Port 8001)...
start /MIN "MARIE Voice" python server_voice.py
echo [MARIE] Waiting 5 seconds for systems to warm up...
timeout /t 5 /nobreak >nul
echo [MARIE] Launching Body (GUI)...
python main.py
echo [MARIE] Closing all services...
taskkill /IM python.exe /F
pause